
# This file was generated by the {rix} R package on Tue Aug  1 14:56:15 2023
# It uses nixpkgs' revision 96d403ee2479f2070050353b94808209f1352edb for reproducibility purposes
# which will install R version current
# Report any issues to https://github.com/b-rodrigues/rix
    { pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/96d403ee2479f2070050353b94808209f1352edb.tar.gz") {} }:

      with pkgs;

      let
      my-r = rWrapper.override {
        packages = with rPackages; [
          hyperSpec qs data_table dplyr targets readxl qrencoder units quarto magick rsvg visNetwork reactable Cubist caret future future_apply languageserver
        ];
      };
 other-pkgs = [quarto];
      in
      mkShell {
        buildInputs = [
          my-r
          other-pkgs
          ];
      }
